Repository henperi/safescrow-bend, pull requests merged in 2020-02, with the labels that each got.

#16 Seed 50 users into dev db
  .vscode/settings.json
  package-lock.json
  package.json
  src/db/seeders/index.ts
  src/db/seeders/seedUsers.ts
Labels: Awaiting Review, Completed

#15 ft(address): implement adding of addresses
  .vscode/settings.json
  src/controllers/AddressController.ts
  src/db/db.interface.ts
  src/db/models/address/address.factory.ts
  src/db/models/address/address.interface.ts
  src/db/models/index.ts
  src/db/models/user/user.factory.ts
  src/db/models/user/user.interface.ts
  src/db/seeders/seedUsers.ts
  src/helpers/tokenHelpers.ts
  src/interfaces/Address.interface.ts
  src/interfaces/TokenHelpers.interface.ts
  src/interfaces/User.interface.ts
  src/interfaces/sequelizeAttributes.interface.ts
  src/middlewares/auth.ts
  src/repositories/AddressRepository.ts
  src/repositories/UserRepository.ts
  src/routes/address/AddressSchema.ts
  src/routes/address/addressValidation.ts
  src/routes/address/index.ts
  src/routes/index.ts
  tests/integrationTests/address.spec.ts
  tests/integrationTests/auth.spec.ts
  tests/integrationTests/index.ts
  tests/mocks/address.mock.ts
  tests/mocks/auth.mock.ts
Labels: Completed

#17 ft(wallets): implement user financial wallet
  src/controllers/WalletController.ts
  src/db/db.interface.ts
  src/db/models/escrowWallet/escrowWallet.factory.ts
  src/db/models/escrowWallet/escrowWallet.interface.ts
  src/db/models/index.ts
  src/db/models/mainWallet/mainWallet.factory.ts
  src/db/models/mainWallet/mainWallet.interface.ts
  src/db/models/user/user.factory.ts
  src/db/models/user/user.interface.ts
  src/db/seeders/seedUsers.ts
  src/repositories/EscrowWalletRepository.ts
  src/repositories/MainWalletRepository.ts
  src/repositories/UserRepository.ts
  src/routes/index.ts
  src/routes/wallet/index.ts
  tests/integrationTests/index.ts
  tests/integrationTests/wallets.spec.ts
Labels: Completed, work in progress

#19 ch(code-cleanUp): remove irrelevant try catch blocks
  src/helpers/tokenHelpers.ts
  src/middlewares/auth.ts
  src/repositories/AddressRepository.ts
  src/repositories/EscrowWalletRepository.ts
  src/repositories/MainWalletRepository.ts
  src/repositories/TransactionRepository.ts
  src/repositories/UserRepository.ts
  src/utils/appLogger.ts
Labels: Awaiting Review, Completed

#14 Ft user password reset 165742482
  .circleci/config.yml
  package-lock.json
  package.json
  src/controllers/AuthController.ts
  src/db/models/user/user.interface.ts
  src/helpers/asyncHandler.ts
  src/helpers/tokenHelpers.ts
  src/interfaces/MiddlewareFunction.interface.ts
  src/middlewares/auth.ts
  src/repositories/UserRepository.ts
  src/routes/auth/AuthSchema.ts
  src/routes/auth/authValidations.ts
  src/routes/auth/index.ts
  tests/integrationTests/auth.spec.ts
  tests/unitTests/controllers/AuthController.spec.ts
  tests/unitTests/helpers/asyncHandler.spec.ts
  tests/unitTests/helpers/mocks/tokenHelpers.mock.ts
  tests/unitTests/helpers/tokenHelpers.spec.ts
  tests/unitTests/index.ts
  tests/unitTests/middlewares/auth.spec.ts
  tests/unitTests/routes/auth/authValidations.spec.ts
Labels: Completed
